apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content-job
spec:
  template:
    spec:
      containers:
      - name: copy-content
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - "echo 'Hello from NFS volume!' > /mnt/data/index.html"
        volumeMounts:
        - mountPath: /mnt/data
          name: nfs-volume
      restartPolicy: Never
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
